config/routes.rb
Rails.application.routes.draw do
  root to: "index#main"
  
  get "/about", to: "about#main" 
  
  get "/register", to: "register#new"
  post "/register", to: "register#create"
  
  get "/login", to: "session#new#"
  post "/login", to: "session#create"
  
  delete "/logout", to: "session#destroy"

  get "/password", to: "passwords#edit"
  patch "/password", to: "passwords#update"
  
  get "/password/reset", to: "passwords_resets#new"
  post "/password/reset", to: "passwords_resets#create"
  get "/password/reset/edit", to: "passwords_resets#edit"
  patch "/password/reset/edit", to: "passwords_resets#update"
end

# Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
    attribute :user
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    validates :email, 
        presence: true,
        uniqueness: true,
        format: {with: URI::MailTo::EMAIL_REGEXP}
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
    def main
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    
    before_action :set_current_user
    
    def set_current_user
        if  session[:user_id]
            Current.user = User.find_by(id: session[:user_id])
        end
    end

    def require_user_logged_in!
        redirect_to login_path, alert: "Yo must be logged in to change your password" if Current.user.nil?
    
    end
end

app/controllers/index_controller.rb
class IndexController < ApplicationController
  
end

app/controllers/passwords_controller.rb
class PasswordsController < ApplicationController
    before_action :require_user_logged_in!

    def edit
    end
    
    def update
        if
        Current.user.update(password_params)
            redirect_to root_path, notice: "Password updated"
        else
            render :edit    
        end
    end

    private

    def password_params
        params.require(:user).permit(:password, :password_confirmation)
    end

end

app/controllers/passwords_resets_controller.rb
class PasswordsResetsController < ApplicationController
    def new
    end

    def create
        @user = User.find_by(email: params[:email])
        if @user.present?
            PasswordMailer.with(user: @user).reset.deliver_now
        end
        redirect_to root_path, notice: "If your account exist in our database then go and check your email for further instructions"
    end

    def edit
        @user = User.find_signed!(params[:token], purpose: "reset_password")
        
        rescue ActiveSupport::MessageVerifier::InvalidSignature
        redirect_to password_reset_path, alert: "Your token has expired. Please try again"
    end

    def update
        @user = User.find_signed!(params[:token], purpose: "reset_password")
        if  @user.update(password_params)
            redirect_to login_path, notice: "Your password was reset successfully. You can now log in"
        else
            render :edit
        end
    end

    private

    def password_params
        params.require(:user).permit(:password, :password_confirmation)
    end
end

app/controllers/register_controller.rb
class RegisterController < ApplicationController
    def new
        @user = User.new()
    end
    
    def create
        @user = User.new(user_params)
        @user[:email].downcase
        if @user.save
            session[:user_id] = @user.id
            redirect_to root_path, notice: "Successfully created"
        else
            render :new
        end
    end

    private

    def user_params
        params.require(:user).permit(:email, :password, :password_confirmation)
    end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
    def new
    end

    def create
        user = User.find_by(email: params[:email])
        if  user && user.authenticate(params[:password])
            session[:user_id] = user.id 
            redirect_to root_path, notice: "Logged in"
        else
            flash[:alert] = "Invalid email or password"
            render :new
        end
    end
    
    def destroy
        session[:user_id] = nil
        redirect_to root_path, notice: "Logged out"
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/about/main.html.erb
<div class="d-flex align-items-center justify-content-center">
    <h1>About this app</h1>
</div>

app/views/index/main.html.erb
<div class="d-flex align-items-center justify-content-center">
    <h1>Wellcome to AlfabetA<sub>pp</sub></h1>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlfaBeta</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <%= render partial: "shared/navbar" %>
    <div class="container">
    <%= render partial: "shared/flash" %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/passwords_resets/edit.html.erb
<h1>Reset your password</h1>

<%= form_with model: @user, url: password_reset_edit_path(token: params[:token]) do |form| %>
    <div class="form-floating mb-3">
        <%= form.password_field :password, class: "form-control", placeholder: "Password"%>
        <label for="floatingInput">
            <%= form.object.errors[:password].any? ? "Invalid password format" : "Password" %>
        </label>
    </div>
    <div class="form-floating mb-3">
        <%= form.password_field :password_confirmation, class: "form-control", placeholder: "Password confirmation" %>
        <label for="floatingInput">
            <%= form.object.errors[:password_confirmation].any? ? "Passwords don't match" : "Password confirmation" %>
        </label>
    </div>
    <div>
        <%= form.submit class: "btn btn-secondary", data: { turbo: false } %>
    </div>
<%end%>

app/views/passwords_resets/new.html.erb
<h1>Reset your password</h1>

<%= form_with url: password_reset_path do |form| %>
    <div class="form-floating mb-3">
        <%= form.text_field :email, class: "form-control", placeholder: "example@email.com" %>
        <label for="floatingInput">Email</label>
    </div>
    <div>
        <%= form.submit "Reset your password", class: "btn btn-secondary", data: { turbo: false } %>
    </div>
<%end%>

app/views/register/new.html.erb
<h1> Sign up</h1>
<%= form_with model: @user, local: true, url: register_path do |form| %>
    
    <div class="form-floating mb-3">
        <%= form.text_field :email, class: "form-control", placeholder: "example@email.com" %>
        <label for="floatingInput">
            <%= form.object.errors[:email].any? ? "Invalid email" : "Email" %>
        </label>
    </div>
    <div class="form-floating mb-3">
        <%= form.password_field :password, class: "form-control", placeholder: "Password"%>
        <label for="floatingInput">
            <%= form.object.errors[:password].any? ? "Invalid password format" : "Password" %>
        </label>
    </div>
    <div class="form-floating mb-3">
        <%= form.password_field :password_confirmation, class: "form-control", placeholder: "Password confirmation" %>
        <label for="floatingInput">
            <%= form.object.errors[:password_confirmation].any? ? "Passwords don't match" : "Password confirmation" %>
        </label>
    </div>
    <div>
        <%= form.submit class: "btn btn-secondary", data: { turbo: false } %>
    </div>
<% end %>

app/views/session/new.html.erb
<h1>Log in</h1>

<%= form_with url: login_path do |form| %>
 <div class="form-floating mb-3">
        <%= form.text_field :email, class: "form-control", placeholder: "email@example.com" %>
        <label for="floatingInput">Email</label>
    </div>
    <div class="form-floating mb-3">
        <%= form.password_field :password, class: "form-control", placeholder: "Password" %>
        <label for="floatingInput">Password</label>
    </div>

    <div>
        <%= form.submit "Log in", class: "btn btn-secondary", data: { turbo: false } %>
        <%= link_to "Forgot my password", password_reset_path, class: "btn btn-outline-secondary"%>
    </div>
    
<% end %>

app/views/shared/_flash.html.erb
<% if flash[:notice] %>
<div class="alert alert-info mt-4" role="alert">
<%= flash[:notice] %>
</div>
<%end%>

<% if flash[:alert] %>
<div class="alert alert-warning mt-4" role="alert">
<%= flash[:alert] %>
</div>
<%end%>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary" data-bs-theme="dark">
  <div class="container-fluid">
    <%= link_to "AlfabetA<sub>pp</sub>".html_safe, root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <span class="navbar-text"></span>
        <%= link_to "About", about_path, class: "nav-link #{'active' if current_page?(about_path)}" %>
        <div class="dropdown">
          <a class="nav-link dropdown-toggle" role="button" data-bs-toggle="dropdown" aria-expanded="false">Alphabet</a>
            <div class="dropdown-menu dropdown-menu-dark">
              <a class="dropdown-item" href="#">Cyrillic</a>
              <a class="dropdown-item" href="#">Korean</a>
            </div>
        </div>
      </div>   
    </div>
    <div class="navbar-nav">
      <% if Current.user %>
          <div class="nav-item">
            <%= link_to Current.user.email, password_path, method: :get, class: "nav-link"%>
          </div>
            <%= button_to "Logout", logout_path, method: :delete, class: "btn btn-outline-secondary" %>
        <% else %>
          <div>
            <%= link_to "Log in", login_path, class: "btn #{current_page?(login_path) ? "btn-secondary" : "btn-outline-secondary"}" %>
            <%= link_to "Sign up", register_path, class: "btn #{current_page?(register_path) ? "btn-secondary" : "btn-outline-secondary"}" %>
          </div>
        <% end %>  
    </div>
  </div>
</nav>     